apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: weird-anteater-nodejs 
  janus-idp.io/tekton: weird-anteater-nodejs
  backstage.io/kubernetes-id: weird-anteater-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: weird-anteater-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  